config/routes.rb
SimpleLogin::Application.routes.draw do
  root 'users#new'
  resources :posts, :only => [:destroy, :create] do
      resources :likes, :only => [:create]
  end

  resources :users
  resources :posts, :only => [:create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy] #only need 3 restful routes for Sessions
  get "/signup"  => 'users#new'
  get "/signin" => 'sessions#new'
  get "/signout" => 'sessions#destroy'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :likes
end

app/models/user.rb
class User < ActiveRecord::Base
  #this allows my form to contain a password field and use it on the model side, even though there is no field
  #in my database called password (we used encrypted_password)
  #this what's called a virtual attribute: it exists only for validation purposes
  attr_accessor :password, :password_confirmation

  has_many :posts
  has_many :likes

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name,    :presence   => true,
            :length               => { :maximum => 30 }
  
  validates :last_name,    :presence   => true,
            :length               => { :maximum => 30 }
  
  validates :email,   :presence   => true,
            :format               => { :with => email_regex },
            :uniqueness           => { :case_sensitive => false }
            #this validates the form input
  validates :password,  :presence => true,
            :confirmation         => true,
            :length               => { :within => 4..100 }

  #before the user gets added to DB, run this function.
  before_save :encrypt_password


  #this method encrypts the user's unencrypted login attempt and returns true if the password is a match
  def has_password?(submitted_password)
    self.encrypted_password == encrypt(submitted_password)
  end


  # class method that checks whether the user's email and submitted password are valid
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end


 # private
    def encrypt_password
      # generate a unique salt if it's a new user
      # self.password uses the attr_accessor we defined above to allow me to grab the inputed password 
      self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{self.password}") if self.new_record?
    
      # encrypt the password and store that in the encrypted_password field
      self.encrypted_password = encrypt(self.password)  #this self.password is what's in the post data!
    end

    # encrypt the password using both the salt and the passed password
    def encrypt(pass)
      Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
    end
end

# form data -> UPW
# S = SHA2(UPW, time)
#  PW = SHA2 (

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  #allow all controllers to have access to the sessions helper
  include SessionsHelper
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
  	@like = Post.find(params[:post_id]).likes.build(like_params)
  	@like.user = current_user
  	if @like.save
  		flash[:notice] = 'liked!'
  		redirect_to users_path
  	else
  		render :text => "cue explosions and death!"
  	end
  end

    private
  	def like_params
  		params.require(:like).permit(:like)
  	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
  	# use and build are similar, make sure to know both
  	@post = current_user.posts.build(post_params)
  	
  	if @post.save
  		flash[:notice] = 'added new post!!'
  		#back to the index method of the users controller
  		redirect_to users_path
  	else
  		render :text => 'what happened?'
  	end


  end

  def destroy

  	 @post = Post.find(params[:id])
    if current_user == @post.user
      if @post.delete
        flash[:message] = "Post DELETED succesfully"
        redirect_to users_path
      else
        flash[:message] = "Post CANNOT be deleted"
        redirect_to users_path
      end
    else
      flash[:notice] = "You can only delete your own posts!"
       redirect_to users_path
    end
  end

  private
  	# STRONG PARMAS
  	def post_params
  		params.require(:post).permit(:text)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #bring up a form for a new session aka login form
  def new
  end

  #create the session resource ie, let user log in
  def create
    #this references the funciton we made in user.rb
    user = User.authenticate(params[:email], params[:password])
  	if user.nil?
  		flash[:error] = "couldn't find a user with those credentials"
      #if there is an error, redirect back to login
      redirect_to new_session_path
  	else
  		sign_in user #helper function
      #redirect to index where we have the wall
  		redirect_to users_path
  	end

  end

  def destroy
  	sign_out #helper function 
  	redirect_to signin_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new #form to make new user
    @user = User.new
  end

  def create #restful route to make new user!
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:notice] = 'New user created!'
      redirect_to signin_path 
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end
  def show
    @user = User.find(params[:id])
  end

  #Since we're building the wall, I want to make the index method the wall page
  def index
    @post = Post.new
    @posts = Post.all.order(:created_at => :desc)
    @like = Like.all
  end
  #define strong parameters!
  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
    #set the value of the current user, IE use the method below
    self.current_user=(user)
  end
  
  # setter method, set the value of the current user as an instance variable!
  def current_user=(user)
    @current_user = user
  end

  # getter method, returns info of current user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  #if there is a current user, IE someone is logged in, this function returns TRUE!
  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    #resets the current user to nil using the current_user= setter method
    self.current_user = nil
  end

  #this function returns true if the user I pass to the function is equal the current user signed in
  def current_user?(user)
    user == self.current_user 
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleLogin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>The Wall</h1>
<h2>Hello <%= current_user.first_name %></h2>
<%= link_to('Log off', signout_path) %><br>
<%= flash[:notice] if flash[:notice]%>
<hr>
<%= form_for(@post) do |f|%>
	<%= f.text_area :text %><br>
<%= f.submit "add your post!" %>
<% end %>

<h2>Posts</h2>

<% @posts.each do |post|%>
	<p><%= post.user.first_name %> says:</p>
	<h3><%= post.text %> </h3>
	<p><%= link_to 'view user', user_path(post.user) %></p>
	<p><%= link_to 'delete post', post_path(post), method: :delete %></p>

	<p>likes: <%= post.likes.count %></p>
	<%= form_for([post, post.likes.build]) do |f|%>
		<%= f.hidden_field :like, :value => 2 %>
		<%= f.submit 'Like!' %>
	<% end %>
<%end %>

app/views/users/new.html.erb
<h1>Register</h1>
<p>This where you register!</p>
<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<p><%= error %></p>
	<% end %>
<% end %>


<%= form_for(@user) do |f| %>
  <%= f.label :first_name, 'your first name:' %><br>
  <%= f.text_field :first_name %><br>
  <%= f.label :first_name, 'your last name:' %><br>
  <%= f.text_field :last_name %><br>
  <%= f.label :email, 'your email' %><br>
  <%= f.text_field :email %><br>
  <%= f.label :password, 'your password' %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation, 'password:' %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit 'register' %>
<% end %>
<a href="signin">sign in!</a>

app/views/users/show.html.erb
<h1>Here is the info on <%= @user.first_name %></h1>
<p>Posts: <%=@user.posts.count %></p>
<p>Likes: <%=@user.likes.count %></p>
<%= link_to 'go back', users_path %>